POST http://localhost:3003/api/blogs
Content-Type: application/json

 {
      "title": "rest testi",
      "author": "testest",
      "url": "https://www.google.com",
      "likes":"69"
    
      
    }



  